version: "3.8"
services:
  minio:
    image: "quay.io/minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
    command: minio server /data/minio --console-address ":9001"

  clamav:
    image: "clamav/clamav:latest"
    ports:
      - "3310:3310"
    #command: ["clamd"]

  # App backend
  api:
    image: cyberapi
    ports:
      - "8080:8080"
    environment:
      - MINIO_A_KEY=access
      - MINIO_S_KEY=secret
    depends_on:
      - clamav
      - minio


