version: "3.8"
services:
  minio:
    image: "quay.io/minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
    command: minio server /data/minio --console-address ":9001"


